### ISSUE TITLE
corpus comparison

### ISSUE THREAD

**Issue by sardarjaf** [ghomasHudson/italkiCorpus#23]
A fair comparison would be also on number of sentences, etc.

**Comment by sardarjaf** [comment]
Table  2 includes stats on number of documents, sentences (not yet) and words for italki and TOEFL.

**Comment by ghomasHudson** [comment]
| Corpus | Number of Sentences  | 
|---|---|
| TOEFL | 200050  |
| italki     | 1068991  |

**Comment by sardarjaf** [comment]
Do you have the figures for number of sentences per language, I think you have it somewhere because you used that info for generating figure 7(a). I found the python script in the figure folder for the words but not for sentences.

**Comment by ghomasHudson** [comment]
| Language      | Number of Sentences (italki) | Number of Sentences (TOEFL) |
| ----------- | ----------- | ----------- |
| ARA  | 67222  | 13813 |
| CHI  | 148801  | 19883 |
| FRE  | 82431  | 18662 |
| GER  | 19087  | 19769 |
| HIN  | 36436  | 19620 |
| ITA  | 83923  | 14588 |
| JPN  | 170351  | 19171 |
| KOR  | 149522  | 20530 |
| SPA  | 136722  | 15695
| TEL  |  3064 | 18626
| TUR  | 45125  | 19693
| |
| **Total**  | 942684  | 200050

**Comment by sardarjaf** [comment]
Table updated

**Comment by ghomasHudson** [comment]
@sardarjaf Am making steady progress - I'll be in Durham tomorrow morning (free before 10 or after 11:30) if you're around for a quick update?

**Comment by sardarjaf** [comment]
Hi Thomas,

9:00-10:00 is good for me.

sardar
________________________________

**Comment by sardarjaf** [comment]
Hi Thomas,

Is it possible to upload the dataset to a public repository such as Github please and add a URL in the corpus. Currently, you github only has  python scripts.


________________________________

**Comment by sardarjaf** [comment]
Great. Once you do that please let me know so I add a footnote to the paper.
________________________________

**Comment by ghomasHudson** [comment]
Added link on github readme
